config/routes.rb
Rails.application.routes.draw do
mount Attachinary::Engine => "/attachinary"
  devise_for :users
    root to: 'pages#home'

  get "/contact" => "pages#contact"
  resources :plans
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plan.rb
class Plan < ApplicationRecord
  has_attachment :img


end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
   def home
    @plan = Plan.all
  end
  def team
    # ...
  end
  def contact
    # ...
  end
end

app/controllers/plans_controller.rb
class PlansController < ApplicationController
   def index
      @plans = Plan.all
  end

  def show
    @plan = Plan.find(params[:id])
  end

  def new
    @plan = Plan.new
  end
  def create
    @plan = Plan.new(plan_params)
   if @plan.save
    redirect_to plans_path
   else
     render :new
   end
  end



 private

  def plan_params
    params.require(:plan).permit(:name, :author, :img, :doc)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plan_helper.rb
module PlanHelper
end

app/helpers/plans_helper.rb
module PlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title>PLATFORM</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" integrity="sha384-MIwDKRSSImVFAZCVLtU0LMDdON6KVCrZHyVQQj6e8wIEJkW4tvwqXrbMIya1vriY" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js" integrity="sha384-ux8v3A6CPtOTqOzMKiuo3d/DomGaaClxFYdCu2HPMBEkf6x2xiDyJ7gkXU0MWwaD" crossorigin="anonymous"></script>
     <style type="text/css">
    a {text-decoration: none;}
   a:hover {text-decoration: none;}
  </style>
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= render "shared/footer" %>
    <%= render "shared/analytics" %>
    <%= javascript_include_tag 'application' %>
    <%= cloudinary_js_config %>
  </body>
</html>

app/views/pages/contact.html.erb
contact

app/views/pages/home.html.erb
<%= render "shared/bannerhome" %>
<br>
<%= render "shared/planhome" %>

app/views/pages/team.html.erb
team

app/views/plans/_form.html.erb
<%= simple_form_for @plan do |f| %>
      <%= f.input :name, as: :url, label: "which name?" %>
      <%= f.input :author, as: :text, label: "which author?" %>
      <%= f.input :img, as: :attachinary %>
       <%= f.input :doc, as: :url, label: "Download link Doc 3D",input_html: { value: 'http://' } %>
      <%= f.button :submit, "Add", class: "btn btn-primary" %>
  <% end %>D

app/views/plans/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1 class="text-center"> All products </h1>
      <% @plans.each do |plan| %>
      <div class="product">
 <%= link_to plan_path(plan) do %>
        
          <%= cl_image_tag plan.img.path, class:"card-img-top card-index", alt:"Card image cap" %>
          
         <div class='product-body'>
            <h3 class="ttext"><%= plan.name %></h3>
            <p class="ttext"><%= plan.author %></p>
           <% end %>
          </div>
          <ul class="list-inline product-controls">
            <li>
              <%= link_to plan_path(plan) do %>
                <i class="fa fa-eye"></i>
              <% end %>
            </li>

          </ul>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/plans/new.html.erb
<div class=" text-center container">

  <h1> NEW GIF</h1>

<%= render "form" %>
</div>

app/views/plans/show.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%);">

  <div class="banner-content">
    <h1><%= @plan.name %></h1>
    <p><%= @plan.author %></p>
    <%= link_to "Download", @plan.doc, class:"navbar-wagon-item navbar-wagon-button btn btn-warning"  %>
  </div>
</div>

app/views/shared/_bannerhome.html.erb
<% if user_signed_in? %>
    <div class="container">

      <h1 class="text-center">I'am IN</h1>
     




<% else %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('background.jpg');">
    <div class="banner-content">
      <h1>Log you</h1>
      <p>FIND BEST ENGINEERING TOOLS</p>
      <%= link_to "GET IT", new_user_registration_path, class: "btn btn-primary btn-lg" %>
    </div>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>

</footer>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/" class="navbar-wagon-brand">
   <%= image_tag "logo.png" %>   <h13>  3D</h13>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">



    <!-- Text link -->

      <%= link_to "All product", plans_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <%= link_to "contact", contact_path, class: "navbar-wagon-item navbar-wagon-link" %>
      <% if user_signed_in? %>

    <!-- Profile picture and dropdown -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="http://placehold.it/50x50" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">

          <li> <%= link_to "log out", destroy_user_session_path, method: :delete %> </li>
        </ul>
      </div>
    </div>

    <!-- Button (call-to-action) -->

    <%= link_to "ADD 3D", new_plan_path, class:"navbar-wagon-item  btn btn-lg btn-info"  %>

      <% else %>
      <%= link_to "Sign UP", new_user_registration_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
      <%= link_to "Log in", new_user_session_path, class:"navbar-wagon-item navbar-wagon-button btn" %>
  <% end %>





  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>

</div>

app/views/shared/_planhome.html.erb
<div class="container">
  <div class="card-deck-wrapper">
    <div class="card-deck">
 <% @plan.each do |plan| %>


            <div class="card card-long text-center">
              <%= cl_image_tag plan.img.path, class:"card-img-top cardy", alt:"Card image cap" %>
              <div class="card-block"><%= plan.name %> <br>
              <%= plan.author %><br>
             <%= link_to "show", plan_path(plan), class:"btn btn-sm btn-warning"%></div>
            </div>

    <% end %>
    </div>
  </div>
</div>